name: Upload LaTeX Build
on:
  push:
    tags:
      - "*"
jobs:
  build_latex:
    if: github.repository == 'ChyenGCY/Chenyu_CV'
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Tree All project
        run: sudo apt install tree;tree

      - name: Branch name
        id: branch_name
        run: |
          echo "SOURCE_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
          echo "SOURCE_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
          echo "SOURCE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: tag name output
        run: |
          echo SOURCE_NAME: ${SOURCE_NAME}
          echo SOURCE_BRANCH: ${SOURCE_BRANCH}
          echo SOURCE_TAG: ${SOURCE_TAG}
        env:
          SOURCE_NAME: ${{ steps.branch_name.outputs.SOURCE_NAME }}
          SOURCE_BRANCH: ${{ steps.branch_name.outputs.SOURCE_BRANCH }}
          SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            CV.tex
            resume.tex

      - name: Tree All project
        run: sudo apt install tree;tree

      - uses: actions/upload-artifact@v4
        with:
          name: PDF_files
          path: |
            CV.pdf
            resume.pdf

      - name: release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./CV.pdf
            ./resume.pdf
          prerelease: false
          generate_release_notes: true

      - name: look files
        run: |
          tree
